Repository BeyondPong/Frontend, pull requests merged in 2024-07, with the labels that each got.

#116 Bug: 친구추가 및 삭제 버튼 attribute 잘 받아오도록 수정
  frontend/static/css/profile.css
  frontend/static/js/view/Profile.js
Labels: Bug, Refactor

#117 Refactor: paddle 움직임버그 수정
  frontend/static/js/game/remoteGame.js
Labels: Feature, Refactor

#119 Refactor: 토너먼트이슈 수정
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Refactor

#120 Feature: 프로필 history에 텍스트 크기 조정 기능 추가
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/view/Profile.js
Labels: Feature

#122 Merge: 메인으로 머지
  frontend/static/css/2fa.css
  frontend/static/css/game.css
  frontend/static/css/play.css
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/api/deleteAPI.js
  frontend/static/js/api/getAPI.js
  frontend/static/js/api/patchAPI.js
  frontend/static/js/api/postAPI.js
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/router/router.js
  frontend/static/js/state/Registry.js
  frontend/static/js/utility/env.js
  frontend/static/js/utility/pathToRegex.js
  frontend/static/js/view/2FA.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Merge

#123 Merge: env .gitignore추가
  .gitignore
  frontend/static/js/utility/env.js
Labels: Merge

#127 Feature: 회원가입 탈퇴 모달 추가
  frontend/static/css/play.css
  frontend/static/css/profile.css
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/router/router.js
  frontend/static/js/state/Registry.js
  frontend/static/js/utility/beforeUnload.js
  frontend/static/js/view/Profile.js
Labels: Feature
