Repository BeyondPong/Frontend, pull requests merged in 2024-06, with the labels that each got.

#28 Feature: profile 페이지 내 friends UI 추가
  frontend/static/css/index.css
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/view/Profile.js
Labels: Feature

#29 Refactor: profile 내 history table을 API 데이터 개수만큼 생성하도록 변경
  frontend/static/js/view/Profile.js
Labels: Refactor

#30 Feature: search API GET,POST 적용
  frontend/static/css/index.css
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/api/api.js
  frontend/static/js/view/Profile.js
Labels: Feature

#33 Feature: profile 이미지(아바타), 상태메세지 수정 기능 추가
  frontend/static/assets/1.png
  frontend/static/assets/2.png
  frontend/static/assets/3.png
  frontend/static/assets/4.png
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/api/api.js
  frontend/static/js/view/Profile.js
Labels: Feature

#35 Feature: 언어변경 API 적용
  frontend/static/js/State/Registry.js
  frontend/static/js/api/api.js
Labels: Feature

#38 Feature: Three.js이용 탁구게임 렌더링
  frontend/static/assets/localPlayModalImg.png
  frontend/static/css/game.css
  frontend/static/css/index.css
  frontend/static/css/play.css
  frontend/static/css/responsive.css
  frontend/static/js/Router/Router.js
  frontend/static/js/api/api.js
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/utility/blurBackGround.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Feature

#41 Merge: 6월 1주차 머지
  frontend/static/assets/1.png
  frontend/static/assets/2.png
  frontend/static/assets/3.png
  frontend/static/assets/4.png
  frontend/static/assets/localPlayModalImg.png
  frontend/static/css/game.css
  frontend/static/css/index.css
  frontend/static/css/play.css
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/Router/Router.js
  frontend/static/js/State/Registry.js
  frontend/static/js/api/api.js
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/utility/blurBackGround.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Merge

#43 Feature: 로그인 구현
  frontend/static/js/Router/Router.js
  frontend/static/js/State/Registry.js
  frontend/static/js/api/api.js
  frontend/static/js/view/Main.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Feature

#44 Refactor: 불필요 Import제거
  frontend/static/js/Router/Router.js
  frontend/static/js/State/Registry.js
  frontend/static/js/api/api.js
  frontend/static/js/view/Main.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Refactor

#45 Feature: 선호언어에 따라 profile UI 추가 적용 및 login을 위한 API headers 추가
  frontend/static/js/State/Registry.js
  frontend/static/js/api/api.js
  frontend/static/js/view/Profile.js
Labels: Feature

#47 Feature: profile 친구 찾기 관련 alert을 모달로 변경
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/State/Registry.js
  frontend/static/js/view/Profile.js
Labels: Feature

#49 Feature: 토너먼트 게임 시작 전 UI 적용
  frontend/static/css/play.css
  frontend/static/css/profile.css
  frontend/static/js/game/localGame.js
  frontend/static/js/index.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/Play.js
Labels: Feature

#51 Feature: 2FA 모달
  frontend/static/css/2fa.css
  frontend/static/css/index.css
  frontend/static/css/responsive.css
  frontend/static/js/index.js
  frontend/static/js/router/router.js
  frontend/static/js/utility/check2FA.js
  frontend/static/js/utility/checkLogin.js
  frontend/static/js/view/2FA.js
  frontend/static/js/view/Main.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Feature

#53 Feature: profile 내 친구 목록 및 친구 삭제 API 적용
  frontend/static/js/api/api.js
  frontend/static/js/router/router.js
  frontend/static/js/view/Profile.js
Labels: Feature

#55 Feature: profile 내 친구 온/오프라인 상태 API 적용
  frontend/static/js/view/Profile.js
Labels: Feature

#56 Feature: 리모트게임, 소켓연결
  frontend/static/css/play.css
  frontend/static/css/responsive.css
  frontend/static/js/api/api.js
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/index.js
  frontend/static/js/router/router.js
  frontend/static/js/view/Play.js
Labels: Feature

#57 Fix: 로컬게임 버그 수정
  frontend/static/js/game/localGame.js
Labels: Bug

#59 Bug: 게임에서 유저상태 웹소켓 정상종료 되도록 수정
  frontend/static/js/router/router.js
Labels: Bug

#64 Feature: 토너먼트 게임 내 웹소켓 연결
  frontend/static/js/view/Play.js
Labels: Feature

#65 Feature: 회원탈퇴 버튼 구현
  frontend/static/css/profile.css
  frontend/static/js/api/api.js
  frontend/static/js/router/router.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/Profile.js
Labels: Feature

#67 Feature: 토너먼트 게임에서 닉네임 중복검사 API 적용
  frontend/static/css/index.css
  frontend/static/css/play.css
  frontend/static/css/responsive.css
  frontend/static/js/api/api.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/Play.js
Labels: Feature

#69 Feature: GDPR문구 추가
  frontend/static/css/2fa.css
  frontend/static/js/router/router.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/2FA.js
Labels: Feature

#71 Feature: 웹소켓 매니저 기능 구현
  frontend/static/js/router/router.js
  frontend/static/js/state/WebSocketManager.js
  frontend/static/js/view/Play.js
Labels: Feature

#72 Feature: remote 임시 게임
  frontend/static/js/game/remoteGame.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/Play.js
Labels: Feature

#73 Bug: 웹 소켓 에러해결
  frontend/static/js/api/api.js
  frontend/static/js/state/WebSocketManager.js
  frontend/static/js/view/Play.js
Labels: Bug

#74 Feature: 리모트게임 백엔드적용
  frontend/static/js/api/api.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/state/WebSocketManager.js
  frontend/static/js/view/2FA.js
  frontend/static/js/view/Play.js
Labels: Feature

#76 Feature: 토너먼트 대진표 UI 추가
  frontend/static/css/play.css
  frontend/static/css/responsive.css
  frontend/static/js/api/api.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Feature

#78 Feature: 패들 움직임 추가
  frontend/static/js/game/remoteGame.js
Labels: Feature

#79 Refactor: game_start를 한번만 보내도록 수정
  frontend/static/js/game/remoteGame.js
  frontend/static/js/view/Play.js
Labels: Refactor

#81 Feature: 토너먼트 대진표에 웹소켓 유저의 데이터 실시간 연동
  frontend/static/assets/tournament_avatar.png
  frontend/static/css/play.css
  frontend/static/css/responsive.css
  frontend/static/js/view/Play.js
Labels: Feature

#83 Style: 토너먼트 대진표의 결승 플레이어 기본아바타 변경
  frontend/static/assets/tournamentAvatar.png
  frontend/static/assets/tournamentFinalAvatar.png
  frontend/static/js/view/Play.js
Labels: Style

#85 Feature: 2FA버튼 다시 못 누르게
  frontend/static/css/main.css
  frontend/static/css/responsive.css
  frontend/static/data/history.json
  frontend/static/data/information.json
  frontend/static/data/search.json
  frontend/static/js/api/api.js
  frontend/static/js/api/deleteAPI.js
  frontend/static/js/api/getAPI.js
  frontend/static/js/api/patchAPI.js
  frontend/static/js/api/postAPI.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/router/router.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/2FA.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Feature, Refactor, Style

#88 Feature: 네트워크 끊고 다시 시작
  frontend/static/js/game/remoteGame.js
  frontend/static/js/view/Play.js
Labels: Bug

#91 Refactor: 로컬게임 큰 화면에서 진행
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/view/2FA.js
  frontend/static/js/view/Play.js
Labels: Feature, Refactor

#92 Style: 2FA, 정책 버튼 및 모달 css 조정
  frontend/static/css/2fa.css
  frontend/static/css/responsive.css
  frontend/static/js/view/2FA.js
Labels: Style

#94 Bug: 회원가입 직후 아바타 변경없이 저장 시 400 에러 수정
  frontend/static/js/view/Profile.js
Labels: Bug

#98 Refactor: GDPR 수정
  frontend/static/css/2fa.css
  frontend/static/js/api/postAPI.js
  frontend/static/js/view/2FA.js
Labels: Refactor

#99 Refactor: 토너먼트 로직 추가
  frontend/static/js/game/remoteGame.js
  frontend/static/js/view/Play.js
Labels: Refactor

#100 Refactor: 로그인이 안되어 있을 시 프로필 페이지 비활성화 처리
  frontend/static/js/view/Main.js
Labels: Refactor

#103 Refactor: 모든 곳에서 탭으로 이동 및 엔터로 클릭 가능하도록 변경
  frontend/static/css/play.css
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Refactor

#106 Merge: 메인으로 머지
  frontend/static/css/2fa.css
  frontend/static/css/main.css
  frontend/static/css/play.css
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/js/api/postAPI.js
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
  frontend/static/js/view/2FA.js
  frontend/static/js/view/Main.js
  frontend/static/js/view/Play.js
  frontend/static/js/view/Profile.js
Labels: Merge

#107 Refactor: 토너먼트용
  frontend/static/css/game.css
  frontend/static/js/game/localGame.js
  frontend/static/js/game/remoteGame.js
Labels: Refactor

#108 Refactor: 토너먼트 로직 수정
  frontend/static/css/game.css
  frontend/static/js/game/remoteGame.js
Labels: Refactor

#109 Refactor: waitGame위치 수정
  frontend/static/js/game/remoteGame.js
Labels: Refactor

#110 Refactor: finalRound 로직 추가
  frontend/static/css/play.css
  frontend/static/js/game/remoteGame.js
Labels: Refactor

#111 Refactor: 2FA 페이지에 인증코드 전송 버튼 추가 및 타이머 추가
  frontend/static/css/2fa.css
  frontend/static/css/profile.css
  frontend/static/js/api/postAPI.js
  frontend/static/js/state/Registry.js
  frontend/static/js/view/2FA.js
Labels: Feature, Refactor

#113 Refactor: 친구 목록에 친구가 없을 시 특정 문구 띄우기
  frontend/static/css/profile.css
  frontend/static/js/state/Registry.js
  frontend/static/js/view/Profile.js
Labels: Bug, Refactor

#114 Refactor: 토너먼트 로직 추가
  frontend/static/css/play.css
  frontend/static/js/game/remoteGame.js
  frontend/static/js/view/Play.js
Labels: Refactor
