Repository BeyondPong/Frontend, pull requests merged in 2024-05, with the labels that each got.

#3 Test: 테스트입니다.
  frontend/index.html
Labels: Test

#4 Docs: issue템플릿 추가
  .github/ISSUE_REQUEST_TEMPLATE.md
Labels: Documentation

#6 Docs: prettierrc파일 추가
  .prettierrc
Labels: Docs

#10 Feature: history json 연결
  frontend/static/js/view/Profile.js
Labels: Feature

#11 Feature: profile 페이지 내 현재선호언어 UI 추가
  frontend/static/css/profile.css
  frontend/static/js/view/Profile.js
Labels: Feature

#14 Feature: profile 페이지 내 Win, Lose를 언어에 따라 변경
  frontend/static/js/State/Registry.js
  frontend/static/js/view/Profile.js
Labels: Feature

#15 Docs: README.md 오타 수정
  README.md
Labels: Docs

#17 Refactor: 플레이페이지 전환 시 스크롤 나타나던 현상
  frontend/static/css/play.css
Labels: Refactor

#21 Feature: vite로 서버실행
  .gitignore
  frontend/package.json
  server.js
Labels: Feature

#24 Feature: profile 페이지 내 search UI 추가
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/data/search.json
  frontend/static/js/view/Profile.js
Labels: Feature

#25 [Merge] 5월 4주차 merge
  .gitignore
  README.md
  frontend/package.json
  frontend/static/css/play.css
  frontend/static/css/profile.css
  frontend/static/css/responsive.css
  frontend/static/data/search.json
  frontend/static/js/Components/Button.js
  frontend/static/js/Components/MainBanner.js
  frontend/static/js/State/Registry.js
  frontend/static/js/api/api.js
  frontend/static/js/view/NotFound.js
  frontend/static/js/view/NotLogin.js
  frontend/static/js/view/Profile.js
  server.js
Labels: Merge
